package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@bfk
public final class asw {
    public static final asl<String> A = asl.a(1, "gads:video:codec_query_mime_types", "");
    public static final asl<Integer> B = asl.a(1, "gads:video:codec_query_minimum_version", 16);
    public static final asl<Boolean> C = asl.a(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final asl<Boolean> D = asl.a(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    public static final asl<String> E = asl.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final asl<String> F = asl.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final asl<String> G = asl.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final asl<Boolean> H = asl.a(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final asl<String> I = asl.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final asl<Boolean> J = asl.a(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final asl<Boolean> K = asl.a(0, "gads:enable_content_fetching", (Boolean) true);
    public static final asl<Integer> L = asl.a(0, "gads:content_length_weight", 1);
    public static final asl<Integer> M = asl.a(0, "gads:content_age_weight", 1);
    public static final asl<Integer> N = asl.a(0, "gads:min_content_len", 11);
    public static final asl<Integer> O = asl.a(0, "gads:fingerprint_number", 10);
    public static final asl<Integer> P = asl.a(0, "gads:sleep_sec", 10);
    public static final asl<Boolean> Q = asl.a(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final asl<Integer> R = asl.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final asl<Boolean> S = asl.a(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final asl<Integer> T = asl.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final asl<Integer> U = asl.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final asl<String> V = asl.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final asl<String> W = asl.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final asl<Boolean> X = asl.a(0, "gad:app_index_enabled", (Boolean) true);
    public static final asl<Boolean> Y = asl.a(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final asl<Boolean> Z = asl.a(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final asl<String> a = asl.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final asl<Boolean> aA = asl.a(1, "gads:enable_ad_loader_manager", (Boolean) true);
    public static final asl<Boolean> aB = asl.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) false);
    public static final asl<Long> aC = asl.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final asl<Boolean> aD = asl.a(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    public static final asl<Boolean> aE = asl.a(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final asl<Boolean> aF = asl.a(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final asl<Boolean> aG = asl.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final asl<String> aH = asl.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final asl<String> aI = asl.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final asl<Integer> aJ = asl.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final asl<Integer> aK = asl.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final asl<Integer> aL = asl.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final asl<String> aM = asl.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final asl<Integer> aN = asl.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final asl<Integer> aO = asl.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final asl<Long> aP = asl.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final asl<Long> aQ = asl.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final asl<Float> aR = asl.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final asl<Float> aS = asl.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final asl<Boolean> aT = asl.a(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final asl<Boolean> aU = asl.a(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    public static final asl<String> aV = asl.a(1, "gads:spherical_video:vertex_shader", "");
    public static final asl<String> aW = asl.a(1, "gads:spherical_video:fragment_shader", "");
    public static final asl<Boolean> aX = asl.a(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final asl<Boolean> aY = asl.a(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final asl<Long> aZ = asl.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final asl<Long> aa = asl.a(0, "gads:app_index:timeout_ms", 1000);
    public static final asl<Boolean> ab = asl.a(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final asl<Boolean> ac = asl.a(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final asl<Boolean> ad = asl.a(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    public static final asl<Boolean> ae = asl.a(0, "gads:ad_key_enabled", (Boolean) false);
    public static final asl<Boolean> af = asl.a(1, "gads:sai:enabled", (Boolean) true);
    public static final asl<Boolean> ag = asl.a(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final asl<Boolean> ah = asl.a(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final asl<Boolean> ai = asl.a(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final asl<Boolean> aj = asl.a(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final asl<String> ak = asl.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final asl<String> al = asl.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final asl<Boolean> am = asl.a(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final asl<Boolean> an = asl.a(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final asl<String> ao = asl.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final asl<Long> ap = asl.a(1, "gads:sai:timeout_ms", -1);
    public static final asl<Integer> aq = asl.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final asl<Boolean> ar = asl.a(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    public static final asl<Boolean> as = asl.a(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final asl<Long> at = asl.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final asl<Boolean> au = asl.a(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final asl<Long> av = asl.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final asl<Long> aw = asl.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final asl<Boolean> ax = asl.a(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final asl<Long> ay = asl.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final asl<Boolean> az = asl.a(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final asl<Boolean> b = asl.a(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final asl<Boolean> bA = asl.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final asl<Boolean> bB = asl.a(0, "gass:enabled", (Boolean) true);
    public static final asl<Boolean> bC = asl.a(0, "gass:enable_int_signal", (Boolean) true);
    public static final asl<Boolean> bD = asl.a(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    public static final asl<Boolean> bE = asl.a(0, "gads:support_screen_shot", (Boolean) true);
    public static final asl<Boolean> bF = asl.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    public static final asl<String> bG = asl.a(1, "gads:sdk_core_constants:caps", "");
    public static final asl<Long> bH = asl.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final asl<Boolean> bI = asl.a(0, "gads:js_flags:mf", (Boolean) false);
    public static final asl<Boolean> bJ = asl.a(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final asl<String> bK = asl.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final asl<String> bL = asl.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final asl<Boolean> bM = asl.a(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final asl<Boolean> bN = asl.a(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final asl<Boolean> bO = asl.a(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final asl<Integer> bP = asl.a(1, "gads:native_video_load_timeout", 10);
    public static final asl<String> bQ = asl.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final asl<Boolean> bR = asl.a(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final asl<Boolean> bS = asl.a(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final asl<Boolean> bT = asl.a(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final asl<Boolean> bU = asl.a(1, "gads:native:overlay_new_fix:enabled", (Boolean) false);
    public static final asl<Boolean> bV = asl.a(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final asl<Boolean> bW = asl.a(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final asl<Boolean> bX = asl.a(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final asl<Long> bY = asl.a(0, "gads:method_tracing:duration_ms", 30000);
    public static final asl<Integer> bZ = asl.a(0, "gads:method_tracing:count", 5);
    public static final asl<Boolean> ba = asl.a(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final asl<Boolean> bb = asl.a(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final asl<Long> bc = asl.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final asl<Boolean> bd = asl.a(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final asl<Boolean> be = asl.a(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    public static final asl<Boolean> bf = asl.a(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final asl<Boolean> bg = asl.a(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    public static final asl<Long> bh = asl.a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final asl<Boolean> bi = asl.a(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final asl<Boolean> bj = asl.a(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final asl<Boolean> bk = asl.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    public static final asl<Long> bl = asl.a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final asl<Long> bm = asl.a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final asl<Long> bn = asl.a(0, "gads:rendering:timeout_ms", 60000);
    public static final asl<Boolean> bo = asl.a(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final asl<Long> bp = asl.a(1, "gads:gestures:task_timeout", 2000);
    public static final asl<Boolean> bq = asl.a(1, "gads:gestures:btt:enabled", (Boolean) false);
    public static final asl<Boolean> br = asl.a(1, "gads:gestures:sss:enabled", (Boolean) false);
    public static final asl<Boolean> bs = asl.a(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final asl<Boolean> bt = asl.a(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final asl<Integer> bu = asl.a(1, "gads:gestures:ts", 1);
    public static final asl<Boolean> bv = asl.a(1, "gads:gestures:tdvs:enabled", (Boolean) false);
    public static final asl<Boolean> bw = asl.a(1, "gads:gestures:tvvs:enabled", (Boolean) false);
    public static final asl<String> bx = asl.a(1, "gads:gestures:pk", "");
    public static final asl<Boolean> by = asl.a(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final asl<Boolean> bz = asl.a(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final asl<Boolean> c = asl.a(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final asl<String> cA = asl.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final asl<String> cB = asl.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final asl<String> cC = asl.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final asl<String> cD = asl.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final asl<Integer> cE = asl.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final asl<Integer> cF = asl.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final asl<Boolean> cG = asl.a(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final asl<Boolean> cH = asl.a(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final asl<Integer> cI = asl.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final asl<Boolean> cJ = asl.a(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final asl<Boolean> cK = asl.a(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final asl<Integer> cL = asl.a(1, "gad:http_redirect_max_count:times", 8);
    public static final asl<Long> cM = asl.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final asl<String> cN = asl.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final asl<Boolean> cO = asl.a(1, "gads:real_test_request:enabled", (Boolean) true);
    public static final asl<Boolean> cP = asl.a(1, "gads:real_test_request:render_webview_label", (Boolean) true);
    public static final asl<Boolean> cQ = asl.a(1, "gads:real_test_request:render_native_label", (Boolean) true);
    private static asl<String> cR = asl.a(0, "gads:sdk_core_experiment_id");
    private static asl<String> cS = asl.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static asl<Boolean> cT = asl.a(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static asl<String> cU = asl.a(0, "gads:request_builder:singleton_webview_experiment_id");
    private static asl<Boolean> cV = asl.a(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static asl<String> cW = asl.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    private static asl<String> cX = asl.a(0, "gads:block_autoclicks_experiment_id");
    private static asl<String> cY = asl.a(0, "gads:spam_app_context:experiment_id");
    private static asl<Integer> cZ = asl.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final asl<Integer> ca = asl.a(0, "gads:method_tracing:filesize", 134217728);
    public static final asl<Long> cb = asl.a(1, "gads:auto_location_timeout", 2000);
    public static final asl<Boolean> cc = asl.a(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    public static final asl<Long> cd = asl.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final asl<String> ce = asl.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final asl<String> cf = asl.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final asl<String> cg = asl.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final asl<String> ch = asl.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final asl<String> ci = asl.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final asl<Long> cj = asl.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final asl<Long> ck = asl.a(1, "gads:parental_controls:timeout", 2000);
    public static final asl<Boolean> cl = asl.a(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final asl<Boolean> cm = asl.a(0, "gads:webview_cookie:enabled", (Boolean) true);
    public static final asl<Boolean> cn = asl.a(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final asl<Boolean> co = asl.a(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final asl<Boolean> cp = asl.a(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final asl<Long> cq = asl.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final asl<Boolean> cr = asl.a(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final asl<Boolean> cs = asl.a(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final asl<String> ct = asl.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final asl<Integer> cu = asl.a(1, "gads:http_assets_cache:time_out", 100);
    public static final asl<Boolean> cv = asl.a(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final asl<Boolean> cw = asl.a(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final asl<Boolean> cx = asl.a(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final asl<Boolean> cy = asl.a(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final asl<Boolean> cz = asl.a(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final asl<String> d = asl.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    private static asl<String> dA = asl.a(0, "gads:gmsg:video_meta:experiment_id");
    private static asl<Long> dB = asl.a(1, "gads:network:cache_prediction_duration_s", 300);
    private static asl<Boolean> dC = asl.a(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static asl<Boolean> dD = asl.a(0, "gads:edu_device_helper:enabled", (Boolean) true);
    private static asl<String> dE = asl.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static asl<String> dF = asl.a(1, "gads:sdk_core_constants:experiment_id");
    private static asl<Boolean> dG = asl.a(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    private static asl<String> dH = asl.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static asl<String> dI = asl.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static asl<String> dJ = asl.a(1, "gads:singleton_webview_native:experiment_id");
    private static asl<Boolean> dK = asl.a(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static asl<String> dL = asl.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static asl<String> dM = asl.b(1, "gads:auto_location_timeout:experiment_id");
    private static asl<Long> dN = asl.a(1, "gads:auto_location_interval", -1);
    private static asl<String> dO = asl.b(1, "gads:auto_location_interval:experiment_id");
    private static asl<String> dP = asl.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    private static asl<String> dQ = asl.a(0, "gads:afs:csa:experiment_id");
    private static asl<Boolean> dR = asl.a(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static asl<Boolean> dS = asl.a(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static asl<Boolean> dT = asl.a(1, "gads:parental_controls:cache_results", (Boolean) true);
    private static asl<String> dU = asl.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static asl<Long> dV = asl.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    private static asl<Integer> dW = asl.a(1, "gads:cache:ad_request_timeout_millis", 250);
    private static asl<Integer> dX = asl.a(1, "gads:cache:max_concurrent_downloads", 10);
    private static asl<Long> dY = asl.a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static asl<Boolean> dZ = asl.a(1, "gads:cache:connection_per_read", (Boolean) false);
    private static asl<String> da = asl.a(0, "gads:video_stream_cache:experiment_id");
    private static asl<Boolean> db = asl.a(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static asl<Float> dc = asl.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static asl<String> dd = asl.a(0, "gads:ad_id_app_context:experiment_id");
    private static asl<String> de = asl.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static asl<Boolean> df = asl.a(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static asl<Float> dg = asl.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static asl<Boolean> dh = asl.a(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static asl<String> di = asl.b(0, "gads:looper_for_gms_client:experiment_id");
    private static asl<Boolean> dj = asl.a(0, "gads:sw_dynamite:enabled", (Boolean) true);
    private static asl<String> dk = asl.a(0, "gads:app_index:experiment_id");
    private static asl<String> dl = asl.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    private static asl<String> dm = asl.a(0, "gads:interstitial_follow_url:experiment_id");
    private static asl<Boolean> dn = asl.a(0, "gads:analytics_enabled", (Boolean) true);

    /* renamed from: do  reason: not valid java name */
    private static asl<Integer> f0do = asl.a(0, "gads:webview_cache_version", 0);
    private static asl<String> dp = asl.b(0, "gads:pan:experiment_id");
    private static asl<Boolean> dq = asl.a(0, "gads:ad_serving:enabled", (Boolean) true);
    private static asl<Boolean> dr = asl.a(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static asl<String> ds = asl.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static asl<Integer> dt = asl.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static asl<Integer> du = asl.a(1, "gads:banner_ad_pool:max_pools", 3);
    private static asl<Integer> dv = asl.a(1, "gads:heap_wastage:bytes", 0);
    private static asl<Boolean> dw = asl.a(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static asl<Boolean> dx = asl.a(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static asl<Boolean> dy = asl.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static asl<Boolean> dz = asl.a(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final asl<Boolean> e = asl.a(0, "gads:block_autoclicks", (Boolean) false);
    private static asl<Long> ea = asl.a(1, "gads:cache:connection_timeout", 5000);
    private static asl<Long> eb = asl.a(1, "gads:cache:read_only_connection_timeout", 5000);
    private static asl<Boolean> ec = asl.a(0, "gads:nonagon:red_button", (Boolean) false);
    private static asl<Boolean> ed = asl.a(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static asl<String> ee = asl.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static asl<Boolean> ef = asl.a(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static asl<String> eg = asl.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static asl<Boolean> eh = asl.a(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static asl<Boolean> ei = asl.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static asl<String> ej = asl.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static asl<Boolean> ek = asl.a(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static asl<String> el = asl.a(1, "gads:nonagon:nativead:ad_unit_exclusions", "(?!)");
    private static asl<Boolean> em = asl.a(1, "gads:nonagon:service:enabled", (Boolean) false);
    private static byte[] en;
    public static final asl<String> f = asl.a(1, "gads:video_exo_player:version", "1");
    public static final asl<Integer> g = asl.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final asl<Integer> h = asl.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final asl<Integer> i = asl.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final asl<Integer> j = asl.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final asl<Integer> k = asl.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final asl<Integer> l = asl.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final asl<Long> m = asl.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final asl<Long> n = asl.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final asl<Integer> o = asl.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final asl<Boolean> p = asl.a(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final asl<String> q = asl.a(1, "gads:video:metric_frame_hash_times", "");
    public static final asl<Long> r = asl.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final asl<Boolean> s = asl.a(1, "gads:video:force_watermark", (Boolean) false);
    public static final asl<Long> t = asl.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final asl<Boolean> u = asl.a(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final asl<Integer> v = asl.a(1, "gads:video:spinner:scale", 4);
    public static final asl<Long> w = asl.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final asl<Boolean> x = asl.a(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final asl<Boolean> y = asl.a(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final asl<Boolean> z = asl.a(1, "gads:memory_bundle:runtime_info", (Boolean) true);

    public static List<String> a() {
        return app.e().a();
    }

    public static void a(Context context) {
        iv.a(context, new asx(context));
        int intValue = ((Integer) app.f().a(dv)).intValue();
        if (intValue > 0 && en == null) {
            en = new byte[intValue];
        }
    }

    public static void a(Context context, int i2, JSONObject jSONObject) {
        app.d();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        app.e().a(edit, 1, jSONObject);
        app.d();
        edit.commit();
    }

    public static List<String> b() {
        return app.e().b();
    }
}
