package com.google.android.gms.internal;

public final class rz {
    public static sa<Long> A = sa.a("measurement.upload.stale_data_deletion_interval", 86400000, 86400000);
    public static sa<Long> B = sa.a("measurement.upload.refresh_blacklisted_config_interval", 604800000, 604800000);
    public static sa<Long> C = sa.a("measurement.upload.initial_upload_delay_time", 15000, 15000);
    public static sa<Long> D = sa.a("measurement.upload.retry_time", 1800000, 1800000);
    public static sa<Integer> E = sa.a("measurement.upload.retry_count", 6, 6);
    public static sa<Long> F = sa.a("measurement.upload.max_queue_time", 2419200000L, 2419200000L);
    public static sa<Integer> G = sa.a("measurement.lifetimevalue.max_currency_tracked", 4, 4);
    public static sa<Integer> H = sa.a("measurement.audience.filter_result_max_count", 200, 200);
    public static sa<Long> I = sa.a("measurement.service_client.idle_disconnect_millis", 5000, 5000);
    private static sa<Boolean> J = sa.a("measurement.service_enabled", true, true);
    private static sa<Boolean> K = sa.a("measurement.service_client_enabled", true, true);
    private static sa<Boolean> L = sa.a("measurement.log_third_party_store_events_enabled", false, false);
    private static sa<Boolean> M = sa.a("measurement.log_installs_enabled", false, false);
    private static sa<Boolean> N = sa.a("measurement.log_upgrades_enabled", false, false);
    private static sa<Boolean> O = sa.a("measurement.log_androidId_enabled", false, false);
    public static sa<Boolean> a = sa.a("measurement.upload_dsid_enabled", false, false);
    public static sa<Boolean> b = sa.a("measurement.event_sampling_enabled", false, false);
    public static sa<String> c = sa.a("measurement.log_tag", "FA", "FA-SVC");
    public static sa<Long> d = sa.a("measurement.ad_id_cache_time", 10000, 10000);
    public static sa<Long> e = sa.a("measurement.monitoring.sample_period_millis", 86400000, 86400000);
    public static sa<Long> f = sa.a("measurement.config.cache_time", 86400000, 3600000);
    public static sa<String> g = sa.a("measurement.config.url_scheme", "https", "https");
    public static sa<String> h = sa.a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com");
    public static sa<Integer> i = sa.a("measurement.upload.max_bundles", 100, 100);
    public static sa<Integer> j = sa.a("measurement.upload.max_batch_size", 65536, 65536);
    public static sa<Integer> k = sa.a("measurement.upload.max_bundle_size", 65536, 65536);
    public static sa<Integer> l = sa.a("measurement.upload.max_events_per_bundle", 1000, 1000);
    public static sa<Integer> m = sa.a("measurement.upload.max_events_per_day", 100000, 100000);
    public static sa<Integer> n = sa.a("measurement.upload.max_error_events_per_day", 1000, 1000);
    public static sa<Integer> o = sa.a("measurement.upload.max_public_events_per_day", 50000, 50000);
    public static sa<Integer> p = sa.a("measurement.upload.max_conversions_per_day", 500, 500);
    public static sa<Integer> q = sa.a("measurement.upload.max_realtime_events_per_day", 10, 10);
    public static sa<Integer> r = sa.a("measurement.store.max_stored_events_per_app", 100000, 100000);
    public static sa<String> s = sa.a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a");
    public static sa<Long> t = sa.a("measurement.upload.backoff_period", 43200000, 43200000);
    public static sa<Long> u = sa.a("measurement.upload.window_interval", 3600000, 3600000);
    public static sa<Long> v = sa.a("measurement.upload.interval", 3600000, 3600000);
    public static sa<Long> w = sa.a("measurement.upload.realtime_upload_interval", 10000, 10000);
    public static sa<Long> x = sa.a("measurement.upload.debug_upload_interval", 1000, 1000);
    public static sa<Long> y = sa.a("measurement.upload.minimum_delay", 500, 500);
    public static sa<Long> z = sa.a("measurement.alarm_manager.minimum_interval", 60000, 60000);
}
