package com.google.android.gms.internal;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.TimeUnit;

@bfk
public final class v extends pp {
    public static final Parcelable.Creator<v> CREATOR = new x();
    public final long A;
    public final String B;
    public final float C;
    public final int D;
    public final int E;
    public final boolean F;
    public final boolean G;
    public final String H;
    public final boolean I;
    public final String J;
    public final boolean K;
    public final int L;
    public final Bundle M;
    public final String N;
    public final arg O;
    public final boolean P;
    public final Bundle Q;
    public final String R;
    public final String S;
    public final String T;
    public final boolean U;
    public final List<Integer> V;
    public final String W;
    public final List<String> X;
    public final int Y;
    public final boolean Z;
    public final int a;
    public final boolean aa;
    public final boolean ab;
    public final Bundle b;
    public final aoy c;
    public final apc d;
    public final String e;
    public final ApplicationInfo f;
    public final PackageInfo g;
    public final String h;
    public final String i;
    public final String j;
    public final jp k;
    public final Bundle l;
    public final int m;
    public final List<String> n;
    public final Bundle o;
    public final boolean p;
    public final int q;
    public final int r;
    public final float s;
    public final String t;
    public final long u;
    public final String v;
    public final List<String> w;
    public final String x;
    public final auv y;
    public final List<String> z;

    v(int i2, Bundle bundle, aoy aoy, apc apc, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, jp jpVar, Bundle bundle2, int i3, List<String> list, Bundle bundle3, boolean z2, int i4, int i5, float f2, String str5, long j2, String str6, List<String> list2, String str7, auv auv, List<String> list3, long j3, String str8, float f3, boolean z3, int i6, int i7, boolean z4, boolean z5, String str9, String str10, boolean z6, int i8, Bundle bundle4, String str11, arg arg, boolean z7, Bundle bundle5, String str12, String str13, String str14, boolean z8, List<Integer> list4, String str15, List<String> list5, int i9, boolean z9, boolean z10, boolean z11) {
        this.a = i2;
        this.b = bundle;
        this.c = aoy;
        this.d = apc;
        this.e = str;
        this.f = applicationInfo;
        this.g = packageInfo;
        this.h = str2;
        this.i = str3;
        this.j = str4;
        this.k = jpVar;
        this.l = bundle2;
        this.m = i3;
        this.n = list;
        this.z = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.o = bundle3;
        this.p = z2;
        this.q = i4;
        this.r = i5;
        this.s = f2;
        this.t = str5;
        this.u = j2;
        this.v = str6;
        this.w = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.x = str7;
        this.y = auv;
        this.A = j3;
        this.B = str8;
        this.C = f3;
        this.I = z3;
        this.D = i6;
        this.E = i7;
        this.F = z4;
        this.G = z5;
        this.H = str9;
        this.J = str10;
        this.K = z6;
        this.L = i8;
        this.M = bundle4;
        this.N = str11;
        this.O = arg;
        this.P = z7;
        this.Q = bundle5;
        this.R = str12;
        this.S = str13;
        this.T = str14;
        this.U = z8;
        this.V = list4;
        this.W = str15;
        this.X = list5;
        this.Y = i9;
        this.Z = z9;
        this.aa = z10;
        this.ab = z11;
    }

    private v(Bundle bundle, aoy aoy, apc apc, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, jp jpVar, Bundle bundle2, int i2, List<String> list, List<String> list2, Bundle bundle3, boolean z2, int i3, int i4, float f2, String str5, long j2, String str6, List<String> list3, String str7, auv auv, long j3, String str8, float f3, boolean z3, int i5, int i6, boolean z4, boolean z5, String str9, String str10, boolean z6, int i7, Bundle bundle4, String str11, arg arg, boolean z7, Bundle bundle5, String str12, String str13, String str14, boolean z8, List<Integer> list4, String str15, List<String> list5, int i8, boolean z9, boolean z10, boolean z11) {
        this(24, bundle, aoy, apc, str, applicationInfo, packageInfo, str2, str3, str4, jpVar, bundle2, i2, list, bundle3, z2, i3, i4, f2, str5, j2, str6, list3, str7, auv, list2, j3, str8, f3, z3, i5, i6, z4, z5, str9, str10, z6, i7, bundle4, str11, arg, z7, bundle5, str12, str13, str14, z8, list4, str15, list5, i8, z9, z10, z11);
    }

    public v(w wVar, long j2, String str, String str2, String str3) {
        this(wVar.a, wVar.b, wVar.c, wVar.d, wVar.e, wVar.f, (String) jx.a(wVar.Q, ""), wVar.g, wVar.h, wVar.j, wVar.i, wVar.k, wVar.l, wVar.m, wVar.o, wVar.p, wVar.q, wVar.r, wVar.s, wVar.t, wVar.u, wVar.v, wVar.w, wVar.x, wVar.y, j2, wVar.z, wVar.A, wVar.B, wVar.C, wVar.D, wVar.E, wVar.F, (String) jx.a(wVar.G, "", 1, TimeUnit.SECONDS), wVar.H, wVar.I, wVar.J, wVar.K, wVar.L, wVar.M, wVar.N, wVar.O, str, str2, str3, wVar.P, wVar.R, wVar.S, wVar.n, wVar.T, wVar.U, wVar.V, wVar.W);
    }

    public final void writeToParcel(Parcel parcel, int i2) {
        int a2 = ps.a(parcel);
        ps.a(parcel, 1, this.a);
        ps.a(parcel, 2, this.b, false);
        ps.a(parcel, 3, (Parcelable) this.c, i2, false);
        ps.a(parcel, 4, (Parcelable) this.d, i2, false);
        ps.a(parcel, 5, this.e, false);
        ps.a(parcel, 6, (Parcelable) this.f, i2, false);
        ps.a(parcel, 7, (Parcelable) this.g, i2, false);
        ps.a(parcel, 8, this.h, false);
        ps.a(parcel, 9, this.i, false);
        ps.a(parcel, 10, this.j, false);
        ps.a(parcel, 11, (Parcelable) this.k, i2, false);
        ps.a(parcel, 12, this.l, false);
        ps.a(parcel, 13, this.m);
        ps.b(parcel, 14, this.n, false);
        ps.a(parcel, 15, this.o, false);
        ps.a(parcel, 16, this.p);
        ps.a(parcel, 18, this.q);
        ps.a(parcel, 19, this.r);
        ps.a(parcel, 20, this.s);
        ps.a(parcel, 21, this.t, false);
        ps.a(parcel, 25, this.u);
        ps.a(parcel, 26, this.v, false);
        ps.b(parcel, 27, this.w, false);
        ps.a(parcel, 28, this.x, false);
        ps.a(parcel, 29, (Parcelable) this.y, i2, false);
        ps.b(parcel, 30, this.z, false);
        ps.a(parcel, 31, this.A);
        ps.a(parcel, 33, this.B, false);
        ps.a(parcel, 34, this.C);
        ps.a(parcel, 35, this.D);
        ps.a(parcel, 36, this.E);
        ps.a(parcel, 37, this.F);
        ps.a(parcel, 38, this.G);
        ps.a(parcel, 39, this.H, false);
        ps.a(parcel, 40, this.I);
        ps.a(parcel, 41, this.J, false);
        ps.a(parcel, 42, this.K);
        ps.a(parcel, 43, this.L);
        ps.a(parcel, 44, this.M, false);
        ps.a(parcel, 45, this.N, false);
        ps.a(parcel, 46, (Parcelable) this.O, i2, false);
        ps.a(parcel, 47, this.P);
        ps.a(parcel, 48, this.Q, false);
        ps.a(parcel, 49, this.R, false);
        ps.a(parcel, 50, this.S, false);
        ps.a(parcel, 51, this.T, false);
        ps.a(parcel, 52, this.U);
        ps.a(parcel, 53, this.V, false);
        ps.a(parcel, 54, this.W, false);
        ps.b(parcel, 55, this.X, false);
        ps.a(parcel, 56, this.Y);
        ps.a(parcel, 57, this.Z);
        ps.a(parcel, 58, this.aa);
        ps.a(parcel, 59, this.ab);
        ps.a(parcel, a2);
    }
}
